#!/bin/bash
# Runs rclone bisync with automatic error handling for common scenarios:
# - First run of bisync
# - Empty directories

script_debug=1
script_verbose=1
log_file='autosync.log'

debugme() {
    [[ $script_debug = 1 ]] && "$@" || :
}

logme(){
	# logme [msg]
	echo $1 | tee -a tmp/autosync.log
}

logmev(){
  # logme [heredoc] [file-to-cat]
	if [[ $script_verbose = 1 ]]; then
		awk '{print "    "$0}' <<- EOF | tee -a tmp/autosync.log
			[ $1 ]
			$(cat $2)
			---
		EOF
	fi
}

bisync(){
    # bisync [local] [remote] [flags]
    rclone bisync \
        $1 $2 \
        --verbose \
        --workdir "tmp/cache" \
        $3
}

autosync-run(){
    # autosync-run [local] [remote] [flags]
    logme 'Running autosync-run'
    tmp_file="autosync.tmp"

    if bisync $1 $2 &> $tmp_file; then
				logmev 'autosync.tmp - sucess case' autosync.tmp
        logme 'Autosync succeded'
        return 0
    fi
		logmev 'autosync.tmp - before retry' autosync.tmp

    # Deal with no prior run case (.lst doesn't exit on cache folder)
    if grep -q 'error: cannot find prior Path1 or Path2 listings' "$tmp_file"; then
        logme 'No prior sync. Retrying with --resync'
        rclone test makefile 1 $1/rclone_keep &> /dev/null
        if bisync $1 $2 --resync &> $tmp_file; then
            logme 'Autosync first run succeded'
        else
            logme "Autosync first run failed"
        fi
    fi

		logmev 'autosync.tmp - after retry' autosync.tmp
}

autosync-run "$@"
logme ''
rm autosync.tmp
